### ISSUE TITLE
翻译任务认领说明

### ISSUE THREAD

**Issue by QC-L** [windicss/docs-cn#2]
# 翻译任务认领说明

> 注意：
>
> 1. 一次尽量只认领一篇，给其他小伙伴留些机会~
>
> 2. 认领开始前，请务必阅读 [翻译流程说明](https://github.com/windicss/docs-cn/issues/1)

从 Todo List 中选取未被人领取过的文章：

未被领取过：

* [ ] installation

领取过：

* [ ] installation (@QC-L)

领取过，已完成：

* [x] installation (@QC-L) #3

**领取方式，在本 issues 下评论即可。**

认领任务格式：

```markdown
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  installation | @QC-L | 2021.05.18 - 2021.05.20 | -
```

示例效果：

Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  installation | @QC-L | 2021.05.18 - 2021.05.20 | -

当完成时，请修改自己的认领评论，添加 PR 信息：

Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  installation | @QC-L | 2021.05.18 - 2021.05.20 | #3

## 任务认领列表

Todo List:

- [x] [guide](https://github.com/windicss/docs-cn/tree/main/guide/)
  - [x] [configuration](https://github.com/windicss/docs-cn/tree/main/guide/configuration.md) (@KimYangOfCat) #11 
  - [x] [extractions](https://github.com/windicss/docs-cn/tree/main/guide/extractions.md) (@yangchaojun) #15 
  - [x] [index](https://github.com/windicss/docs-cn/tree/main/guide/index.md) (@QC-L) #5 
  - [x] [installation](https://github.com/windicss/docs-cn/tree/main/guide/installation.md) (@QC-L) #3 
  - [x] [migration](https://github.com/windicss/docs-cn/tree/main/guide/migration.md) (@HerbertHe) #18 
- [x] [features](https://github.com/windicss/docs-cn/tree/main/features/)
  - [x] [value-auto-infer](https://github.com/windicss/docs-cn/tree/main/features/value-auto-infer.md) (@HerbertHe) #28 
  - [x] [analyzer](https://github.com/windicss/docs-cn/tree/main/features/analyzer.md) (@HerbertHe) #17 
  - [x] [dark-mode](https://github.com/windicss/docs-cn/tree/main/features/dark-mode.md) (@HerbertHe) #19 
  - [x] [RTL](https://github.com/windicss/docs-cn/tree/main/features/rtl.md) (@justforuse) #100
  - [x] [directives](https://github.com/windicss/docs-cn/tree/main/features/directives.md) (@HerbertHe) #22 
  - [x] [important-prefix](https://github.com/windicss/docs-cn/tree/main/features/important-prefix.md) (@HerbertHe) #23 
  - [x] [index](https://github.com/windicss/docs-cn/tree/main/features/index.md) (@HerbertHe) #27 
  - [x] [attributify](https://github.com/windicss/docs-cn/tree/main/features/attributify.md) (@watonyweng) #110
  - [x] [responsive-design](https://github.com/windicss/docs-cn/tree/main/features/responsive-design.md) (@HerbertHe) #24 
  - [x] [shortcuts](https://github.com/windicss/docs-cn/tree/main/features/shortcuts.md) (@HerbertHe) #26 
  - [x] [variant-groups](https://github.com/windicss/docs-cn/tree/main/features/variant-groups.md) (@cabbage9) #47
- [x] [editors](https://github.com/windicss/docs-cn/tree/main/editors)
  - [x] [webstorm](https://github.com/windicss/docs-cn/tree/main/editors/webstorm.md) (@HerbertHe) #7 
  - [x] [vscode](https://github.com/windicss/docs-cn/tree/main/editors/vscode.md) (@HerbertHe) #6 
- [x] [integrations](https://github.com/windicss/docs-cn/tree/main/integrations)
  - [x] [cli](https://github.com/windicss/docs-cn/tree/main/integrations/cli.md) (@kmq116) #36 
  - [x] [gridsome](https://github.com/windicss/docs-cn/tree/main/integrations/gridsome.md) (@kmq116) #35 
  - [x] [javascript](https://github.com/windicss/docs-cn/tree/main/integrations/javascript.md) (@HerbertHe) #30
  - [x] [nuxt](https://github.com/windicss/docs-cn/tree/main/integrations/nuxt.md)(@KimYangOfCat ) #40 
  - [x] [postcss](https://github.com/windicss/docs-cn/tree/main/integrations/postcss.md) (@HerbertHe) #16 
  - [x] [rollup](https://github.com/windicss/docs-cn/tree/main/integrations/rollup.md) (@HerbertHe) #13 
  - [x] [svelte](https://github.com/windicss/docs-cn/tree/main/integrations/svelte.md) (@HerbertHe) #12 
  - [x] [vite](https://github.com/windicss/docs-cn/tree/main/integrations/vite.md) (@satrong) #21 
  - [x] [vue-cli](https://github.com/windicss/docs-cn/tree/main/integrations/vue-cli.md) (@guangzan) #10 
  - [x] [webpack](https://github.com/windicss/docs-cn/tree/main/integrations/webpack.md) (@HerbertHe) #14 
- [x] [plugins](https://github.com/windicss/docs-cn/tree/main/plugins)
  - [x] [index](https://github.com/windicss/docs-cn/tree/main/plugins/index.md) (@watonyweng) #125
  - [x] [interfaces](https://github.com/windicss/docs-cn/tree/main/plugins/interfaces.md) (@Megrax) #29
  - [x] [transform](https://github.com/windicss/docs-cn/tree/main/plugins/transform.md) (@Megrax)  #31
  - [x] [official](https://github.com/windicss/docs-cn/tree/main/plugins/official/)
    - [x] [line-clamp](https://github.com/windicss/docs-cn/tree/main/plugins/official/line-clamp.md) (@watonyweng) #117
    - [x] [aspect-ratio](https://github.com/windicss/docs-cn/tree/main/plugins/official/aspect-ratio.md) (@watonyweng) #116
    - [x] [filters](https://github.com/windicss/docs-cn/tree/main/plugins/official/filters.md)(@watonyweng) #62
    - [x] [forms](https://github.com/windicss/docs-cn/tree/main/plugins/official/forms.md) (@Megrax) #38  
    - [x] [scroll-snap](https://github.com/windicss/docs-cn/tree/main/plugins/official/scroll-snap.md) (@HerbertHe) #111 
    - [x] [typography](https://github.com/windicss/docs-cn/tree/main/plugins/official/typography.md) (@watonyweng) #115
  - [x] [community](https://github.com/windicss/docs-cn/tree/main/plugins/community/)
    - [x] [animations](https://github.com/windicss/docs-cn/tree/main/plugins/community/animations.md) (@KimYangOfCat) #39
    - [x] [heropatterns](https://github.com/windicss/docs-cn/tree/main/plugins/community/heropatterns.md)  (@watonyweng) #118
    - [x] [interaction-variants](https://github.com/windicss/docs-cn/tree/main/plugins/community/interaction-variants.md) (@Megrax) #48 
    - [x] [question-mark](https://github.com/windicss/docs-cn/tree/main/plugins/community/question-mark.md) (@Megrax) #44
    - [x] [scrollbar](https://github.com/windicss/docs-cn/tree/main/plugins/community/scrollbar.md) (@Megrax) #45
- [ ] [posts](https://github.com/windicss/docs-cn/tree/main/posts)
  - [ ] [api](https://github.com/windicss/docs-cn/tree/main/posts/api.md)
  - [ ] [attributify](https://github.com/windicss/docs-cn/tree/main/posts/attributify.md)
  - [ ] [extension-updates](https://github.com/windicss/docs-cn/tree/main/posts/extension-updates.md)
  - [x] [language](https://github.com/windicss/docs-cn/tree/main/posts/language.md) (@watonyweng) #72 
  - [ ] [modes](https://github.com/windicss/docs-cn/tree/main/posts/modes.md)
  - [ ] [plugin](https://github.com/windicss/docs-cn/tree/main/posts/plugin.md)
  - [x] [v22](https://github.com/windicss/docs-cn/tree/main/posts/v22.md)(@huzhengen) #61
  - [x] [v24](https://github.com/windicss/docs-cn/tree/main/posts/v24.md)(@huzhengen) #60
  - [ ] [v30-5](https://github.com/windicss/docs-cn/tree/main/posts/v30-5.md)
  - [ ] [v30-utilities](https://github.com/windicss/docs-cn/tree/main/posts/v30-utilities.md)
  - [ ] [v30](https://github.com/windicss/docs-cn/tree/main/posts/v30.md)
  - [ ] [v31](https://github.com/windicss/docs-cn/tree/main/posts/v31.md)
  - [x] [v34](https://github.com/windicss/docs-cn/tree/main/posts/v34.md) (@qwecxzpoi) #136
  - [x] [story](https://github.com/windicss/docs-cn/tree/main/posts/story.md)(@kmq116) #63
- [x] [utilities](https://github.com/windicss/docs-cn/tree/main/utilities)
  - [x] [svg](https://github.com/windicss/docs-cn/tree/main/utilities/svg.md) (@HerbertHe) #51 
  - [x] [backgrounds](https://github.com/windicss/docs-cn/tree/main/utilities/backgrounds.md) (@watonyweng) #77
  - [x] [behaviors](https://github.com/windicss/docs-cn/tree/main/utilities/behaviors.md) (@watonyweng) #98
  - [x] [borders](https://github.com/windicss/docs-cn/tree/main/utilities/borders.md) (@luckyJeffy) #54 
  - [x] [colors](https://github.com/windicss/docs-cn/tree/main/utilities/colors.md) (@cabbage9) #49
  - [x] [container](https://github.com/windicss/docs-cn/tree/main/utilities/container.md) (@zrr1999) #52
  - [x] [display](https://github.com/windicss/docs-cn/tree/main/utilities/display.md) (@keylxiao) #71
  - [x] [effects](https://github.com/windicss/docs-cn/tree/main/utilities/effects.md) (@watonyweng) #74
  - [x] [filters](https://github.com/windicss/docs-cn/tree/main/utilities/filters.md) (@watonyweng) #107
  - [x] [flexbox](https://github.com/windicss/docs-cn/tree/main/utilities/flexbox.md) (@HerbertHe) #68 
  - [x] [grid](https://github.com/windicss/docs-cn/tree/main/utilities/grid.md)(@watonyweng) #91
  - [x] [index](https://github.com/windicss/docs-cn/tree/main/utilities/index.md) (@watonyweng) #73
  - [x] [positioning](https://github.com/windicss/docs-cn/tree/main/utilities/positioning.md) (@watonyweng) #104
  - [x] [sizing](https://github.com/windicss/docs-cn/tree/main/utilities/sizing.md) (@watonyweng) #95
  - [x] [spacing](https://github.com/windicss/docs-cn/tree/main/utilities/spacing.md) (@watonyweng) #83
  - [x] [tables](https://github.com/windicss/docs-cn/tree/main/utilities/tables.md) (@watonyweng) #92
  - [x] [transforms](https://github.com/windicss/docs-cn/tree/main/utilities/transforms.md) (@watonyweng) #76
  - [x] [transitions](https://github.com/windicss/docs-cn/tree/main/utilities/transitions.md) (@watonyweng) #75
  - [x] [typography](https://github.com/windicss/docs-cn/tree/main/utilities/typography.md) (@watonyweng) #66
  - [x] [variants](https://github.com/windicss/docs-cn/tree/main/utilities/variants.md) (@watonyweng) #79

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  installation | @QC-L | 2021.05.25 - 2021.05.25 | -

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide | configuration | @KimYangOfCat | 2021.05.26 - 2021.05.28 | -

**Comment by QC-L** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  index | @QC-L | 2021.05.26 - 2021.05.26 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
editors |  vscode | @HerbertHe | 2021.05.26 - 2021.05.26 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
editors |  webstorm | @HerbertHe  | 2021.05.26 - 2021.05.26 | -

**Comment by guangzan** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations  |  vue-cli  | @guangzan | 2021.05.26 - 2021.05.27 | -

**Comment by satrong** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations |  vite | @satrong | 2021.05.26 - 2021.05.30 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations |  svelte | @HerbertHe  | 2021.05.26 - 2021.05.26 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations |  rollup | @HerbertHe | 2021.05.26 - 2021.05.26 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations |  webpack | @HerbertHe  | 2021.05.26 - 2021.05.26 | -

**Comment by yangchaojun** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  extractions | @yangchaojun | 2021.05.27 - 2021.05.28 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations |  postcss | @HerbertHe  | 2021.05.27 - 2021.05.27 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  analyzer | @HerbertHe | 2021.05.27 - 2021.05.27 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  migration | @HerbertHe  | 2021.05.27 - 2021.05.27 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  dark-mode | @HerbertHe  | 2021.05.27 - 2021.05.27 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features | directives | @HerbertHe | 2021.05.28 - 2021.05.28 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features | important-prefix | @HerbertHe | 2021.05.28 - 2021.05.28 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  responsive-design | @HerbertHe | 2021.05.28 - 2021.05.28 | -

**Comment by Megrax** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
plugins |  interfaces | @Megrax | 2021.05.29 - 2021.06.01 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  shortcuts | @HerbertHe | 2021.05.29 - 2021.05.29 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  index | @HerbertHe | 2021.05.29 - 2021.05.29 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  value-auto-infer | @HerbertHe | 2021.05.29 - 2021.05.29 | -

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations |  javascript | @HerbertHe | 2021.05.29 - 2021.05.29 | -

**Comment by Megrax** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
plugins |  transform | @Megrax | 2021.05.29 - 2021.06.01 | -

**Comment by kmq116** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features|  index| @kmq116 | 2021.05.29 - 2021.05.30 | -

**Comment by HerbertHe** [comment]
> Section | Title | 译者 | 完成时间 | PR
> -- | -- | -- | -- | --
> features|  index| @kmq116 | 2021.05.29 - 2021.05.30 | -
> 

@kmq116 这个翻译过了。

**Comment by KimYangOfCat** [comment]
> Section	Title	译者	完成时间	PR
> features	index	@kmq116	2021.05.29 - 2021.05.30	-

抱歉，没有及时更新，请重新选择一篇翻译吧

**Comment by kmq116** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
integrations|  cli| @kmq116 | 2021.05.30 - 2021.05.30 | -

**Comment by kmq116** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
gridsome|  integrations| @kmq116  | 2021.05.30 - 2021.05.30 | -

**Comment by kmq116** [comment]
> > 部分
> > 标题
> > 译者
> > 完成时间
> > 公关
> > 
> > 
> > 
> > 
> > 特征
> > 指数
> > @ kmq116
> > 2021.05.29-2021.05.30
> > --
> 
> @ kmq116这个翻译过了。

>@sorry,我翻译完了才看到下面有人领取过了

> > Section
> > Title
> > 译者
> > 完成时间
> > PR
> > 
> > 
> > 
> > 
> > features
> > index
> > @kmq116
> > 2021.05.29 - 2021.05.30
> > -
> 
> @kmq116 这个翻译过了。
> @HerbertHe sorry，翻译完了才看到

**Comment by Megrax** [comment]
Section | Title | Subtitle | 译者 | 完成时间 | PR
-- | -- | -- | -- | -- | --
plugins |  official | forms | @Megrax  | 2021.05.31 - 2021.06.02 | -

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
community |  animations | @KimYangOfCat | 2021.06.04 - 2021.06.05 | -

**Comment by KimYangOfCat** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
 integrations |  nuxt | @KimYangOfCat | 2021.06.06 - 2021.06.08 | -

**Comment by Megrax** [comment]
Section | Title | Subtitle | 译者 | 完成时间 | PR
-- | -- | -- | -- | -- | --
plugins |  community | question-mark | @Megrax  | 2021.06.09 - 2021.06.12 | -

**Comment by Megrax** [comment]
Section | Title | Subtitle | 译者 | 完成时间 | PR
-- | -- | -- | -- | -- | --
plugins |  community | scrollbar | @Megrax  | 2021.06.09 - 2021.06.12 | -

**Comment by cabbage9** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features | variant-groups | @cabbage9 | 2021.06.10 - 2021.06.10 | -

**Comment by Megrax** [comment]
Section | Title | Subtitle | 译者 | 完成时间 | PR
-- | -- | -- | -- | -- | --
plugins |  community | interaction-variants | @Megrax  | 2021.06.11 - 2021.06.13 | -

**Comment by cabbage9** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
utilities | colors | @cabbage9 | 2021.06.13 - 2021.06.13 |

**Comment by zrr1999** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
utilities |  container | @zrr1999 | 2021.06.24 - 2021.06.24 | -

**Comment by luckyJeffy** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
guide |  borders | @luckyJeffy | 2021.06.30 - 2021.7.02 | -

**Comment by kmq116** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
posts|  story| @kmq116 | 2021.07.07 - 2021.07.08 | -

**Comment by huzhengen** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
posts | v24 | @huzhengen | 2021.07.07 - 2021.07.08 | -

**Comment by huzhengen** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
posts |  v22 | @huzhengen | 2021.07.07 - 2021.07.07 | -

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| plugins | filters | @watonyweng | 2021.07.07 - 2021.07.08 |  -   |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | typography | @watonyweng | 2021.07.12 - 2021.07.13 |  -    |

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
utilities |  flexbox | @HerbertHe | 2021.07.15 - 2021.07.15 | -

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| posts | language | @watonyweng | 2021.07.15 - 2021.07.17 |  -    |

**Comment by keylxiao** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
utilities | display | @keylxiao | 2021.07.18 - 2021.07.20 | -

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | effects | @watonyweng | 2021.07.21 - 2021.07.23 | -  |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | index | @watonyweng | 2021.07.21 - 2021.07.21 | - |

**Comment by keylxiao** [comment]
> Section	Title	译者	完成时间	PR
> utilities	display	@keylxiao	2021.07.18 - 2021.07.20	#71

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | transitions | @watonyweng | 2021.07.23 - 2021.07.25 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | transforms | @watonyweng | 2021.07.26 - 2021.07.28 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | variants | @watonyweng | 2021.07.29 - 2021.07.31 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | backgrounds | @watonyweng | 2021.08.02 - 2021.08.05 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | spacing | @watonyweng | 2021.08.23 - 2021.08.25 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | gird | @watonyweng | 2021.09.03 - 2021.09.05 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | tables | @watonyweng | 2021.09.18 - 2021.09.20 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | sizing | @watonyweng | 2021.09.25 - 2021.09.27 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | behaviors | @watonyweng | 2021.09.28 - 2021.09.30 | - |

**Comment by justforuse** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
features |  rtl | @justforuse | 2021.09.29 - 2021.09.29 | #100

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | positioning | @watonyweng | 2021.10.01 - 2021.10.03 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| utilities | filters | @watonyweng | 2021.10.14 - 2021.10.16 | - |

**Comment by HerbertHe** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
plugins |  official/scroll-snap | @HerbertHe  | 2021.10.31 - 2021.10.31 | -

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| plugins | typography | @watonyweng | 2021.11.13 - 2021.11.15 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| plugins | official/aspect-ratio | @watonyweng | 2021.11.16 - 2021.11.18 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| plugins | official/line-clamp | @watonyweng | 2021.11.19 - 2021.11.21 | - |

**Comment by watonyweng** [comment]
| Section |  Title  |    译者     |        完成时间         |  PR  |
| :-----: | :-----: | :---------: | :---------------------: | :--: |
| plugins | community/heropatterns | @watonyweng | 2021.11.28 - 2021.11.30 | - |

**Comment by qwecxzpoi** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
posts |  v34 | @qwecxzpoi | 2022.03.28- 2022.03.30 | -

**Comment by wty9sky** [comment]
Section | Title | 译者 | 完成时间 | PR
-- | -- | -- | -- | --
posts | v31 | @wty9sky | 2023.02.16 - 2021.02.20 | -
